#include "GrandCityMobileGameMode.h"
#include "GrandCityMobileCharacter.h"
#include "GrandCityMobileGameState.h"
#include "GrandCityMobilePlayerController.h"
#include "GrandCityMobilePlayerState.h"
#include "GrandCityAccountAuthSubsystem.h"
#include "GrandCityServerRegistrySubsystem.h"
#include "Engine/World.h"
#include "Engine/GameInstance.h"
#include "GameFramework/PlayerController.h"

AGrandCityMobileGameMode::AGrandCityMobileGameMode(){DefaultPawnClass=AGrandCityMobileCharacter::StaticClass();PlayerControllerClass=AGrandCityMobilePlayerController::StaticClass();PlayerStateClass=AGrandCityMobilePlayerState::StaticClass();GameStateClass=AGrandCityMobileGameState::StaticClass();}
void AGrandCityMobileGameMode::BeginPlay(){Super::BeginPlay();if(HasAuthority()&&GetWorld()){GetWorldTimerManager().SetTimer(ProfileCheckpointTimer,this,&AGrandCityMobileGameMode::SaveAllPlayerProfiles,60.0f,true,60.0f);if(UGameInstance* GI=GetGameInstance())if(UGrandCityServerRegistrySubsystem* R=GI->GetSubsystem<UGrandCityServerRegistrySubsystem>())R->StartServerRegistration();}}
void AGrandCityMobileGameMode::BeginServerDrain(){if(!HasAuthority())return;if(AGrandCityMobileGameState* GS=GetGameState<AGrandCityMobileGameState>())GS->bServerDraining=true;if(UGameInstance* GI=GetGameInstance())if(UGrandCityServerRegistrySubsystem* R=GI->GetSubsystem<UGrandCityServerRegistrySubsystem>())R->BeginDraining();UE_LOG(LogTemp,Display,TEXT("Grand City server is now DRAINING; new player sessions will be rejected."));}
FString AGrandCityMobileGameMode::InitNewPlayer(APlayerController* NewPlayer,const FUniqueNetIdRepl& UniqueId,const FString& Options,const FString& Portal){if(const AGrandCityMobileGameState* GS=GetGameState<AGrandCityMobileGameState>())if(GS->bServerDraining)return TEXT("SERVER_DRAINING");const FString Result=Super::InitNewPlayer(NewPlayer,UniqueId,Options,Portal);if(AGrandCityMobilePlayerController* PC=Cast<AGrandCityMobilePlayerController>(NewPlayer)){FString AuthToken,TransferToken,ConnectionTicket;FParse::Value(*Options,TEXT("AuthToken="),AuthToken);FParse::Value(*Options,TEXT("TransferToken="),TransferToken);FParse::Value(*Options,TEXT("ConnectionTicket="),ConnectionTicket);PC->SetAuthCredentials(AuthToken,TransferToken,ConnectionTicket);}return Result;}
void AGrandCityMobileGameMode::PostLogin(APlayerController* NewPlayer){Super::PostLogin(NewPlayer);if(const AGrandCityMobileGameState* GS=GetGameState<AGrandCityMobileGameState>())if(GS->bServerDraining){RejectUnauthenticatedPlayer(Cast<AGrandCityMobilePlayerController>(NewPlayer),TEXT("This server is draining and is not accepting new players."));return;}AGrandCityMobilePlayerController* PC=Cast<AGrandCityMobilePlayerController>(NewPlayer);if(!PC)return;UGameInstance* GI=GetGameInstance();UGrandCityAccountAuthSubsystem* Auth=GI?GI->GetSubsystem<UGrandCityAccountAuthSubsystem>():nullptr;if(!Auth||PC->GetConnectionTicket().IsEmpty()){RejectUnauthenticatedPlayer(PC,TEXT("A secure connection ticket is required. Please sign in again."));return;}TWeakObjectPtr<AGrandCityMobilePlayerController> WeakPC(PC);const FString ServerId=GetGameState<AGrandCityMobileGameState>()?GetGameState<AGrandCityMobileGameState>()->ServerId.ToString():TEXT("GC-AFRICA-01");Auth->ConsumeConnectionTicket(PC->GetConnectionTicket(),ServerId,[this,WeakPC](bool bValid,const FGrandCityAccountIdentity& Identity){AGrandCityMobilePlayerController* Player=WeakPC.Get();if(!Player||!bValid||Identity.AccountId.IsEmpty()){if(Player)RejectUnauthenticatedPlayer(Player,TEXT("The connection ticket is invalid, expired, or belongs to another server."));return;}if(AGrandCityMobilePlayerState* PS=Player->GetPlayerState<AGrandCityMobilePlayerState>()){PS->AccountId=Identity.AccountId;PS->DisplayName=Identity.DisplayName;PS->RegionId=Identity.RegionId;PS->bAuthenticated=false;}UGameInstance* GI=GetGameInstance();UGrandCityAccountAuthSubsystem* AccountAuth=GI?GI->GetSubsystem<UGrandCityAccountAuthSubsystem>():nullptr;if(!AccountAuth){RejectUnauthenticatedPlayer(Player,TEXT("Account service is unavailable."));return;}const FString TargetServerId=GetGameState<AGrandCityMobileGameState>()?GetGameState<AGrandCityMobileGameState>()->ServerId.ToString():TEXT("GC-AFRICA-01");AccountAuth->ClaimSession(Identity.AccountId,TargetServerId,Player->GetTransferToken(),[this,WeakPC](bool bClaimed,const FString&){AGrandCityMobilePlayerController* Claimed=WeakPC.Get();if(!Claimed)return;if(!bClaimed){RejectUnauthenticatedPlayer(Claimed,TEXT("This account is already active on another server or the transfer is invalid."));return;}Claimed->LoadPersistentProfile([this,WeakPC](bool bLoaded){if(AGrandCityMobilePlayerController* Loaded=WeakPC.Get())HandleProfileLoaded(Loaded,bLoaded);});});});}
void AGrandCityMobileGameMode::Logout(AController* Exiting){ProfileReadyPlayers.Remove(Exiting);if(AGrandCityMobilePlayerController* PC=Cast<AGrandCityMobilePlayerController>(Exiting)){const FString AccountId=PC->GetPlayerState<AGrandCityMobilePlayerState>()?PC->GetPlayerState<AGrandCityMobilePlayerState>()->AccountId:FString();const FString ServerId=GetGameState<AGrandCityMobileGameState>()?GetGameState<AGrandCityMobileGameState>()->ServerId.ToString():TEXT("GC-AFRICA-01");PC->SavePersistentProfile([this,AccountId,ServerId](bool){if(UGameInstance* GI=GetGameInstance())if(UGrandCityAccountAuthSubsystem* Auth=GI->GetSubsystem<UGrandCityAccountAuthSubsystem>())if(!AccountId.IsEmpty())Auth->ReleaseSession(AccountId,ServerId,[](bool){});});PC->ClearAuthCredentials();}Super::Logout(Exiting);UpdateOnlinePlayerCount();}
void AGrandCityMobileGameMode::RestartPlayer(AController* NewPlayer){if(!NewPlayer||!HasAuthority()||!ProfileReadyPlayers.Contains(NewPlayer))return;Super::RestartPlayer(NewPlayer);}
void AGrandCityMobileGameMode::HandleProfileLoaded(APlayerController* Player,bool bSuccess){if(!HasAuthority()||!Player)return;if(!bSuccess){RejectUnauthenticatedPlayer(Cast<AGrandCityMobilePlayerController>(Player),TEXT("Unable to load your saved character data."));return;}if(AGrandCityMobilePlayerState* PS=Player->GetPlayerState<AGrandCityMobilePlayerState>())PS->bAuthenticated=true;ProfileReadyPlayers.Add(Player);RestartPlayer(Player);}
void AGrandCityMobileGameMode::RejectUnauthenticatedPlayer(AGrandCityMobilePlayerController* Player,const FString& Reason){if(!Player||!HasAuthority())return;Player->ClientReturnToMainMenuWithTextReason(FText::FromString(Reason));Player->Destroy();}
void AGrandCityMobileGameMode::UpdateOnlinePlayerCount(){if(!HasAuthority()||!GetWorld())return;if(AGrandCityMobileGameState* GS=GetGameState<AGrandCityMobileGameState>())GS->OnlinePlayerCount=GetNumPlayers();}
void AGrandCityMobileGameMode::SaveAllPlayerProfiles(){if(!HasAuthority()||!GetWorld())return;for(FConstPlayerControllerIterator It=GetWorld()->GetPlayerControllerIterator();It;++It)if(AGrandCityMobilePlayerController* PC=Cast<AGrandCityMobilePlayerController>(It->Get()))PC->SavePersistentProfile([](bool){});}
